'use client';

import About from '@/components/about';
import Main from '@/components/main';
import Navbar from '@/components/navbar';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title></title>
        <meta name='description' content='Generated by Me' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar/>
      <Main/>
      <About/>
    </div>
  );
}
